server:
  port: 10010
spring:
  application:
    name: itcast-zuul
zuul:
  routes:
    service-provider: /provider/**
  prefix: /api
      #path: /service-provider/**
      #serviceId: service-provider
      # url: http://localhost:8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
